name: Terraform Destroy

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  authenticate:
    name: Authenticate with AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::123456789012:role/TerraformRole  # Replace with your IAM Role ARN
          aws-region: ${{ secrets.AWS_REGION }}

  terraform_destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    needs: authenticate
    env:
      # Backend configuration via environment variables
      S3_BUCKET: ${{ secrets.TF_S3_BUCKET }}
      S3_KEY: ${{ secrets.TF_S3_KEY }}
      S3_REGION: ${{ secrets.AWS_REGION }}
      DYNAMODB_TABLE: ${{ secrets.TF_DYNAMODB_TABLE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::123456789012:role/TerraformRole  # Replace with your IAM Role ARN
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${S3_BUCKET}" \
            -backend-config="key=${S3_KEY}" \
            -backend-config="region=${S3_REGION}" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${DYNAMODB_TABLE}"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve